# Generated by Django 5.2 on 2025-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
